version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
  database:
    image: "alpine:latest"
    volumes:
      - ./data:/data
    command: sh -c "apk add --no-cache sqlite && sqlite3 /data/banking_app.db"
